### ISSUE TITLE
Move build scripts into main repos, set up CI

### ISSUE THREAD

**Issue by aganders3** [gpilab/conda-distro#2]
Now with conda-forge (and the MacPorts installer) we don't have to build all our dependencies anymore. I think we should move the build scripts (build.sh and meta.yaml) for the framework and core-nodes into their respective repositories, and get rid of this one. Then we should set up Travis CI to build and upload to Anaconda (https://gist.github.com/zshaheen/fe76d1507839ed6fbfbccef6b9c13ed9). Travis is apparently free for all open source projects, and they have both Linux and macOS environments for building. This would also let us more easily build for multiple Python and NumPy versions, which would make installation with conda easier for the end-users with only incremental effort from us.

Ideally we'd also set this up for the ReadPhilips node (see https://github.com/gpilab/philips-data-reader/issues/7), but unfortunately it's closed source so we'd have to pay for Travis or figure something else out.

**Comment by nckz** [comment]
This is awesome!  I'm still looking at the macports install, I got caught up updating all of my existing ports ;).

Travis would be a great CI for the open stuff, and you could always host an internal build server for the Philips repos on gitlab; at least the CI part would be closed and free.

**Comment by aganders3** [comment]
Travis got bought: https://blog.travis-ci.com/2019-01-23-travis-ci-joins-idera-inc

I'm not sure if this really changes anything for us - they claim they'll still offer the free plans for open source. That said, I am going to compare with CircleCI (also have free plans, including Mac environments, for OSS) and others before committing to anything. I'd like to only learn one :).

Also I'd like to revisit packaging the .app version/dmg if it can be automated.

Finally (though this should go in the framework repo) I think the auto-updater needs to get much more robust or be pulled (maybe replaced with a script to do conda update gpi from the proper environment).

**Comment by aganders3** [comment]
Another quick thought: we could try to get gpi added to conda-forge. This might save us from setting up CI at all, and make it easier to install (no need for our custom GPI channel).

https://conda-forge.org/#add_recipe

**Comment by aganders3** [comment]
After some discussion with @borupdaniel I think we're going to skip setting up our own CI and push toward conda-forge as the longer-term solution. Short-term I think it's still a good idea to move the conda build recipes into their respective repositories. This makes sense to me as we stop packaging our own versions of astyle, qimage2ndarray, eigen, fftw, etc.

One more thing to consider is if the framework can be packaged as `noarch` because it's pure python. The only thing I don't understand about creating a `noarch_python` package is how you can restrict *which* versions of Python are compatible (for us this will just be >=3.4 I think, for now).

Some info on noarch packages:
https://www.anaconda.com/condas-new-noarch-packages/

**Comment by aganders3** [comment]
Regarding `noarch` packages:

This may require re-structuring the framework repo to be packaged like a pure python package, and potentially therefore spinning out PyFI as a separate project. Also we would lose control over how `gpi` and `gpi_make` get put in `bin/`, instead relying only on specifying CLI entry points. This is probably not worth it for now (especially if it's going to be built by conda-forge anyway).
